index:
    path: /
    controller: App\Controller\IndexAction

select_player:
    path: /vyber-hrace
    controller: App\Controller\SelectPlayerAction

show_players:
    path: /hraci
    controller: App\Controller\ShowPlayersAction
